language: node_js
node_js:
- '10'
- '12'
script:
- npm run test:ci
- npm run build
after_script:
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
after_success:
- "./.ci/update-gh-pages.sh"
cache: false
env:
  global:
    secure: kU4Tl9tx9BZCpcvxOi0ItDv9J2fO3BH2b04LQNm9m6CFFnR83oxvuN4sxXlePlqDuVAGYJAKVhDkevzkxHW1NLUPSDHi0ISb34ZdCXrwQJ+RO/K/Fdn7VoGkUpmkNnSms5jNY7Ajaz9oxv7HWMfV81QuwEzWPk6zqU16LMBp0b89iE/uu6k5q2kCO6x0w2xojup7V0b91lRRWxzkgRzgN2t6ctLF3/DTi+LHfSkqA53wekDiHMetXJf80ORYGzupS8pZbbk5YMnVBO+bykvWkcl8rASa/zMFk97wULXPaPw9JnPk5+JDfAi1w+410akGb/Qk9qb0dbFKM3U5ZPvlM8RS23KEzTiVrej19kv2QFG8iIuPMR3pQuL+yEdH/qyKIuS3mBLCXS9+M5i0X89L3gaux51PqZtXFfseYcZE5+z/LjdIYpPt7TLC3Lb76kOVWU7IZbVO/0c8xSmjBN27DlKkGzpB6zPDU9uNNy6YG2aNVYbjsz/eMfgo6co4nghEyilAVftJdGT0g4QCANlg9qyzowKbHHQtIJ1XjcFoA6P8uOX/bbu9mOWcLG8g+splefT4e07vB3H9Cr5+OZkPpdMdzuh6LTKCwUo+gwit7DsHDsiEH6pHU45e8egAHYq6IYzzWd0gq7YCKLDBP2DFAAE8ceLhfVvgwyBW5BqQ8AA=
